FAMILIAS_FIJAS = [
    "Frutas",
    "Verduras",
    "Carnes",
    "Pescados",
    "Mariscos",
    "Embutidos",
    "Yogures y postres",
    "Leche y derivados",
    "Quesos",
    "Huevos",
    "Arroz, pastas y legumbres",
    "Conservas",
    "Aceites y vinagres",
    "Snacks",
    "Alimentos preparados",
    "Bolleria",
    "Pan",
    "Cereales",
    "Otros (Desayuno)",
    "Congelados de carne",
    "Congelado de pescado",
    "Congelados de verduras",
    "Postres congelados",
    "Otros congelados",
    "Bebidas no alcohólicas",
    "Bebidas alcohólicas",
    "Cosmética",
    "Higiene",
    "Limpieza del hogar",
    "Productos de cocina"
]
